# Generated by Django 6.0.4 on 2026-05-03 07:09

import dataingestion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dataingestion.models.upload_csv_path)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FILE_CORRUPTED', 'File Corrupted')], default='PROCESSING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('error_file', models.FileField(blank=True, null=True, upload_to=dataingestion.models.upload_error_path)),
                ('error_threshold_exceeded', models.BooleanField(default=False)),
                ('result_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RowError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('column_name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='dataingestion.fileuploadtracking')),
            ],
        ),
    ]
