# Generated by Django 6.0.4 on 2026-05-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataingestion', '0002_fileuploadtracking_rowerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadtracking',
            name='file_type',
            field=models.CharField(choices=[('users', 'Users'), ('stores', 'Stores'), ('mapping', 'Mapping')], default='', max_length=20),
        ),
    ]
