# Generated by Django 6.0.4 on 2026-05-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataingestion', '0003_fileuploadtracking_file_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuploadtracking',
            old_name='file_type',
            new_name='upload_type',
        ),
    ]
