# Generated by Django 6.0.4 on 2026-05-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataingestion', '0004_rename_file_type_fileuploadtracking_upload_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_active',
        ),
    ]
